all:
	g++ -std=c++11 -O0 -o cmv cm_value.cc
	g++ -std=c++11 -O0 -o cmvd cm_value_debug.cc
	g++ -std=c++11 -O0 -o cma cm_array.cc
	g++ -std=c++11 -O0 -o cmad cm_array_debug.cc
	g++ -std=c++11 -O0 -o cmaf cm_array_fixed.cc
